//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserServiceDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Feature
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Feature()
        {
            this.T_Rol_Component_Feature = new HashSet<T_Rol_Component_Feature>();
        }
    
        public int IdFeature { get; set; }
        public string FeatureName { get; set; }
        public short IdComponent { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<long> CreatorUser { get; set; }
    
        public virtual T_Component T_Component { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Rol_Component_Feature> T_Rol_Component_Feature { get; set; }
    }
}
