//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserServiceDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Transactional_Log
    {
        public long IdTranLog { get; set; }
        public long IdUser { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string TableChange { get; set; }
        public Nullable<int> IdRegister { get; set; }
        public string Type { get; set; }
    
        public virtual T_User T_User { get; set; }
    }
}
